### PR TITLE
Update deps using go 1.13

### LINKED ISSUE #532: go 1.13 for client
Track bumping go to 1.13 for client and if there are any concerns.

Checklist:
- [x]  Update go.mod
- [x]  Update test-infra config to relevant changes https://github.com/knative/test-infra/issues/1574
- [x]  Docs

### PR DESCRIPTION
**Pull request by navidshaikh**
Fixes #532

## Proposed Changes
 - Commit results of codegen using go 1.13
 - Update DEVELOPMENT.md to mention go 1.13

### CODE REVIEW

**Comment by navidshaikh** [comment]
/hold

We'll need changes at test-infra side for using go 1.13 for client tests.

**Comment by adrcunha** [comment]
Related/dependency: https://github.com/knative/test-infra/pull/1558

**Comment by chizhg** [comment]
FYI Prow job for client has been updated to use Go 1.13, so this PR is now ready to be merged.

**Pull request merged**
