### PR TITLE
[release-0.19] Backport #1117 #1083 #1113

### PR DESCRIPTION
**Pull request by navidshaikh**
Backport PR for release-v0.19.1 with

- #1117
- #1083 
- #1113 
- Updated CHANGELOG

### CODE REVIEW

**Comment by navidshaikh** [comment]
@BbolroC : can you please add your consent by adding comment `@googlebot I consent.` here ?

**Comment by navidshaikh** [comment]
/test pull-knative-client-unit-tests

    wait_for_ready_test.go:65: assertion failed: expected error to contain "FakeError", got "timeout: blub 'foobar' not ready after 3 seconds"
--- FAIL: TestAddWaitForReady (7.75s)

**Comment by BbolroC** [comment]
@googlebot I consent

**Comment by navidshaikh** [comment]
@googlebot I consent.

**Comment by navidshaikh** [comment]
/retest

       result_collector.go:75: ERROR: Error: Operation cannot be fulfilled on pingsources.sources.knative.dev "testpingsource0": the object has been modified; please apply your changes to the latest version and try again

**Pull request merged**
