### PR TITLE
Fix bogus warning in build.sh

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Review by navidshaikh — APPROVED** [review]
/lgtm
/approve

works nicely
```
➜  client git:(pr/fix-build.sh) ./hack/build.sh 
🚒 Update
⚖️ License
📖 Docs
🚧 Compile
🧪 Test
────────────────────────────────────────────
Version:      v20201015-local-0fa9d958
Build Date:   2020-10-15 10:47:00
Git Revision: 0fa9d958
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.18.0)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.18.0)
  - eventing.knative.dev/v1beta1 (knative-eventing v0.18.0)
```

**Comment by dsimansk** [comment]
The test failure a real error that needs to be addressed. With recent change in Serving GC config, the label `serving.knative.dev/route` is only present in certain condition. 
Related to https://github.com/knative/serving/commit/0852b9f6fe449a0f8c47b6f3a85abef2cb239388 and https://github.com/knative/serving/blob/ee522945f396b7124f7a6a5ae502f88fd2af294f/pkg/reconciler/service/resources/configuration.go#L46-L48.

**Pull request merged**
