### PR TITLE
[Release-0.18] Pin knative deps to release-0.18

### PR DESCRIPTION
**Pull request by ZhiminXiang**
- Pin knative deps to release-0.18
- Use k8s 1.18.8 version

### CODE REVIEW

**Review by maximilien — COMMENTED** [review]
/ok-to-test

**Comment by ZhiminXiang** [comment]
I think when pinning pkg to release-0.18, it requires bumping k8s version to 1.18.8.

**Review by navidshaikh — APPROVED** [review]
The PR also takes care of bumping k8s dep as done separately in #1011 , so we can get this in and close the other. cc: @rhuss

**Comment by ZhiminXiang** [comment]
Can I get an lgtm for this PR?

**Review by navidshaikh — APPROVED** [review]
/lgtm

**Pull request merged**
