### PR TITLE
Fix fetching of Istion latest release

### PR DESCRIPTION
**Pull request by dsimansk**
## Description

Per TODO properly fix the version fetch.

## Changes

 
* Fix fetching of Istion latest release

## Reference

Fixes #

### CODE REVIEW

**Comment by dsimansk** [comment]
/hold

I've added unrelated commit https://github.com/knative/client/pull/1509/commits/d1757f9e77635176490a0b7f3f7fade8609d0c67. That might improve the following "delete broker timeout" flake. 

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1509/pull-knative-client-integration-tests/1455626919981617152

**Comment by dsimansk** [comment]
For the reference, I'll pull the wait code out to the separate PR.
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1509/pull-knative-client-integration-tests-latest-release/1455653754056478720#1:build-log.txt%3A898

**Comment by rhuss** [comment]
/approve
/lgtm

is this still on hold ? Looks good to me.

**Comment by dsimansk** [comment]
/unhold

I was trying hash out some of those E2E. It's good to go now.

**Pull request merged**
