### PR TITLE
chore: Remove deprecated requests/limits flags

### PR DESCRIPTION
**Pull request by dsimansk**
## Description

This PR removes `--requests-cpu,--requests-memory,--limits-cpu,--limits-memory` that should be deprecated already per code comment:
```
// TODO: Flag marked deprecated in release v0.15.0, remove in release v0.18.0
```

@navidshaikh @rhuss @maximilien @daisy-ycguo @itsmurugappan 
If there's any reason or support concern that those flags might be still used/useful, please bring it up.

## Changes

* Remove `--requests-cpu,--requests-memory,--limits-cpu,--limits-memory`

## Reference

Fixes N/A

### CODE REVIEW

**Review by navidshaikh — APPROVED** [review]
/approve
lgtm

thanks @dsimansk !
please add CHANGELOG entry

**Comment by navidshaikh** [comment]
/lgtm

lets get the CHANGELOG added with the v0.19 prep cc: @rhuss

**Comment by dsimansk** [comment]
@navidshaikh ups, I've added changelog already.

**Review by navidshaikh — APPROVED** [review]
/lgtm

**Pull request merged**
