### PR TITLE
Update vendor/knative.dev/test-infra

### PR DESCRIPTION
**Pull request by adrcunha**
Major changes:
* display E2E cluster setup during tests
* fix parsing error for autogenerated code in flaky test reporter
* fix automatic dot releases for 0.10+ branches

Part of https://github.com/knative/test-infra/issues/1542

/cc @grantr

### CODE REVIEW

**Comment by adrcunha** [comment]
Every time I run the integration tests I get a different set of failures... Which makes sense given the amount of red in the CI flow: https://testgrid.knative.dev/client#continuous

/retest

**Comment by rhuss** [comment]
The issue is very likely related to changes on serving master, tracked at #500

**Comment by navidshaikh** [comment]
The tests should be fixed as we merge https://github.com/knative/client/pull/506.

**Pull request merged**
