### PR TITLE
Fixes `limits-memory` and `requests-memory` descriptions

### PR DESCRIPTION
**Pull request by maximilien**
Erroneously showed ‘CPU’ for ‘memory’ in description strings

### CODE REVIEW

**Comment by rhuss** [comment]
/lgtm

the test failure is a general build failure affecting every PR. I'm on it.

**Comment by maximilien** [comment]
> Please also update (auto-generated) docs for `service create` and `service update`.

OK doing this now. Sorry for the delay.

**Comment by maximilien** [comment]
Done: @navidshaikh @rhuss

**Comment by rhuss** [comment]
The test are  flaky 

```
Failed to successfully execute 'kn service update hello --env TARGET=kn -n kne2etests': Execution error: stderr: 'Operation cannot be fulfilled on services.serving.knative.dev "hello": the object has been modified; please apply your changes to the latest version and try again
' error: 'exit status 1'FAIL	github.com/knative/client/test/e2e	1.792s
```

Let's track that in https://github.com/knative/client/issues/100 It looks either a timing issue or indeed an error on our side, that we don't read the service to update before updating or doing something wrong here.

**Pull request merged**
