### PR TITLE
Run e2e CI job against eventing v0.19.1 since nightly is broken

### PR DESCRIPTION
**Pull request by navidshaikh**
The ping source update for sink isnt working as expected.
see https://github.com/knative/eventing/issues/4584

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
/lgtm
/approve

**Comment by navidshaikh** [comment]
see https://github.com/knative/eventing/issues/4584 for more details

**Comment by dsimansk** [comment]
@navidshaikh should it fail with pinned version? 
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1136/pull-knative-client-integration-tests/1331184455745802240#1:build-log.txt%3A975

**Comment by navidshaikh** [comment]
> @navidshaikh should it fail with pinned version?

failed differently, it was flake. @dsimansk this is ready to go now.

**Pull request merged**
