### PR TITLE
add code cov

### LINKED ISSUE #1300: Add codecov coverage tests
### Feature request

Similar to the other Knative projects let's add codecov coverage test so that those stats appear at https://app.codecov.io/gh/knative/client 

Also add a badged to the README.md that contains the overall coverage stats.

### Use case

One of the 1.0 criteria will be a test coverage >= 80% so we should calculate that number with every merge.

### PR DESCRIPTION
**Pull request by itsmurugappan**
## Description

Add code coverage 

## Reference

Fixes #1300

### CODE REVIEW

**Comment by navidshaikh** [comment]
@itsmurugappan : can you add the badge in readme as well ? see https://github.com/knative/serving/edit/main/README.md for ref

**Comment by itsmurugappan** [comment]
added @navidshaikh

**Review by maximilien — APPROVED** [review]
Thx for adding CV
/ok-to-test
/approve
/lgtm

**Pull request merged**
