### PR TITLE
Support multiple NAMEs on service delete

### PR DESCRIPTION
**Pull request by daisy-ycguo**
Partially address #317

## Proposed Changes

* Support multiple NAMEs on `kn service delete`

Release Note:

In the following cases, add a short description of PR to the unreleased section in CHANGELOG.adoc:

- 🧽 Support multiple NAMEs on `kn service delete`

### CODE REVIEW

**Comment by rhuss** [comment]
@daisy-ycguo please rebase on master, this should fix the test issues.

**Comment by daisy-ycguo** [comment]
Thank you for review. Your comment is addressed. An e2e test case is added.

> We definitely need an e2e test for this.
> 
> What happens if the list has bogus services in it. Should the whole command fail or continue. Likely fail as you have implemented but a message to user that the remaining services did not get deleted is likely needed.
> 
> Let's be clear about the failure scenarios and add appropriate tests.
> 
> Thanks for the contribution.

**Comment by daisy-ycguo** [comment]
> looks good to me, please also add a line to CHANGELOG.adoc for this change. thanks !

Thank you for review. I've add a line to CHANGELOG.adoc.

**Pull request merged**
