### PR TITLE
Re-enable markdown link check

### PR DESCRIPTION
**Pull request by navidshaikh**
## Proposed Changes
* Re-enable markdown link check as https://github.com/raviqqe/liche/issues/33 is now fixed,
  see https://github.com/knative/test-infra/pull/1764/
* Update test-infra to latest

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

```
    cli.go:70: ERROR: Operation cannot be fulfilled on apiserversources.sources.eventing.knative.dev "testapisource3": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by dsimansk** [comment]
/retest

Another instance of E2E traffic split flake #694.
```
     --- FAIL: TestTrafficSplit/20:80 (15.50s)
       traffic_split_test.go:113: ramp/up down a revision to 20% adjusting other traffic to accommodate
       traffic_split_test.go:417: assertion failed: error is not nil: expecting 2 targets, got 1 targets targets: ,echo1-rev-2,100,true separator: |

**Pull request merged**
