### PR TITLE
[0.17] Backport 1044 and 10101

### PR DESCRIPTION
**Pull request by navidshaikh**
- Backport:
  - #1044 
  - #1010 
- Update CHANGELOG

### CODE REVIEW

**Comment by rhuss** [comment]
@mpetason Could you please do a `@googlebot I consent.` to mak CLAbot happy ?

**Review by rhuss — APPROVED** [review]
/lgtm 

but @navidshaikh , this is only for #1010 , right ? (not #1044

**Comment by navidshaikh** [comment]
> but @navidshaikh , this is only for #1010 , right ? (not #1044

Added #1044 as well, which is the fix for subscription e2e,  as that might fail in actual patch release job as well. @rhuss

**Comment by navidshaikh** [comment]
@googlebot I consent

@mpetason : can you please add your consent here like above?

**Comment by mpetason** [comment]
@googlebot I consent.

**Pull request merged**
