### PR TITLE
chore: Update k8s dependencies and cleaned up a bit

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by rhuss** [comment]
Move to Kubernetes 1.16.4 als dependency which is the same that serving & eventing 0.12.0 is uing. Had to nail down googlecontainerregistry to fixed commit, so that the dependency on master does not automatically upgrade k8s to 1.17.0.

**Comment by navidshaikh** [comment]
/test pull-knative-client-integration-tests-latest-release

```
Failed to successfully execute 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests6': Execution error: stderr: 'RevisionMissing: Revision "hello-vwfbq-1" referenced in traffic not found.
' error: 'exit status 1'FAIL	knative.dev/client/test/e2e	49.831s
```

**Comment by rhuss** [comment]
@navidshaikh I think its good to merge now.

**Pull request merged**
