### PR TITLE
Remove toolchain directive

### PR DESCRIPTION
**Pull request by dsimansk**
## Description

It's blocking auto-update job to update deps actually.

## Changes

* Remove toolchain directive

## Reference

Fixes #

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by dsimansk** [comment]
@ReToCode ahh it seems like a genuine error. I'm taking a closer look.

**Comment by dsimansk** [comment]
Flake
/retest

**Pull request merged**
