### PR TITLE
Adds revision get command

### LINKED ISSUE #41: Add more details in the output of `revision list` command
`kn revision list` lists only the names of the revisions. Other useful information about the revision could be printed.

### PR DESCRIPTION
**Pull request by navidshaikh**
Fixes #41 

```
./kn revision get
SERVICE   NAME        AGE     CONDITIONS   READY     REASON
n1        n1-twdvc    15h     4 OK / 5     True      
s1        s1-bnpwq    15h     4 OK / 5     True      
s10       s10-xkphp   8m54s   4 OK / 5     True      
s11       s11-4spbx   5s      1 OK / 5     Unknown   Deploying
s12       s12-6284j   65s     5 OK / 5     True      
```

### CODE REVIEW

**Comment by thockin** [comment]
Why am I a reviewer for this?

**Comment by cppforlife** [comment]
@thockin github is prolly confused with all the vendored code. removed...

**Comment by navidshaikh** [comment]
@rhuss @sixolet @cppforlife : Rebased and ready for review, PTAL.

**Pull request merged**
