### PR TITLE
[Automated] Update actions

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
# meta: knative/.github
# main: knative/client
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
  "${GITHUB_WORKSPACE}/main/.github/workflows/"
```
/cc rhuss maximilien
/assign rhuss maximilien

### CODE REVIEW

**Review by maximilien — COMMENTED** [review]
/ok-to-test

**Comment by rhuss** [comment]
Let's discuss our usage of GitHub actions in today's client WG call, but looks good to me.

**Review by rhuss — COMMENTED** [review]
Looks good to me in general, but I have the feeling that some actions could be combined to reduce the number of checks. Of course, it's a trade-off between being too coarse-grained and having some checks not running that also might fail, and too fine-grained which for sure eat up more resources (more containers need to be spin up, every time the source code needs to be checked out again, reviewdog needs to be download multiples times for every CI run).

As these scripts are homogenous across all Knative repos, this is probably not the proper place to discuss this (?)

Also, some short documentation would be helpful which configuration file a repo can create to tune the quality checks. Maybe a `.github/workflows/README.md` ?

**Comment by rhuss** [comment]
Added two issues over there to tackle the issues mentioned above in the review comment:

* https://github.com/knative-sandbox/.github/issues/61
* https://github.com/knative-sandbox/.github/issues/60

**Comment by rhuss** [comment]
Let's merge that and see how it goes

/lgtm
/approve

**Pull request merged**
