### PR TITLE
 Remove unused `--config` option

### PR DESCRIPTION
**Pull request by nak3**
Currently parameters read by `--config` in kn can not be used.
This patch removes the option from the command.

Fixes https://github.com/knative/client/issues/138

### CODE REVIEW

**Comment by cppforlife** [comment]
@sixolet i believe you've added this initially. any thoughts on usefulness of this feature?

**Comment by rhuss** [comment]
@nak3 I guess you need an dependency update / rebase for the tests to pass.
@cppforlife thanks for taking care !

**Comment by nak3** [comment]
@rhuss @cppforlife Thank you! Updated and it looks like all tests were passed.

By the way, I found current `test/presubmit-test.sh` updates some files. I filed it as separated issue here https://github.com/knative/client/issues/163

**Comment by sixolet** [comment]
It was there because it was part of the default cobra boilerplate. We can always reintroduce if we need it.
/lgtm
/approve

**Comment by nak3** [comment]
@sixolet @rhuss @cppforlife Thank you. Rebased (so dropped the LGTM label).

**Comment by maximilien** [comment]
How is this not merged yet when it's been /lgtm by both @cppforlife and @sixolet ?

I see @knative-prow-robot removed the labels. You all need to comment again and /approve.

**Pull request merged**
