### PR TITLE
feat(wait): add sync revision delete operation

### LINKED ISSUE #671: Add `--wait` and `--no-wait` for all delete operation
## Describe the feature:

In order to avoid race conditions when on delete an object and immediately recreate it, by default we should also wait for the end of a delete operation, like we do for `service create` and `service update`.

Therefor a `--wait` and a `--no-wait` option should be added to all "delete" operation. This can reuse our general wait handling util libs.

### PR DESCRIPTION
**Pull request by dsimansk**
Fixes #671 

## Proposed Changes

* Change `revision delete` to wait for completion

### CODE REVIEW

**Comment by dsimansk** [comment]
> TrafficSplit fail

/test pull-knative-client-integration-tests

**Comment by navidshaikh** [comment]
```
        🔥 RevisionMissing: Revision "hello-rsrfx-2" referenced in traffic not found.
```

**Comment by navidshaikh** [comment]
/retest

This isn't flake with asynchronous revision delete, see https://github.com/knative/client/issues/695

**Comment by navidshaikh** [comment]
/retest

```
    --- FAIL: TestTrafficSplit/TagStagingLatest (9.05s)
```

**Comment by navidshaikh** [comment]
/retest

```
--- FAIL: TestRevision (237.94s)
```

last retry, or lets get this in after https://github.com/knative/client/pull/696

**Pull request merged**
