### PR TITLE
chore(e2e): Minor cleanup

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

```
        🦆 kn service update hello --env TARGET=kn --port 8888 --namespace kne2etests0
        ┃ 
        🔥 Operation cannot be fulfilled on services.serving.knative.dev "hello": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by rhuss** [comment]
>   🦆 kn service update hello --env TARGET=kn --port 8888 --namespace kne2etests0
>         ┃ 
>         🔥 Operation cannot be fulfilled on services.serving.knative.dev "hello": the object has been modified; please apply your changes to the latest version and try again

Hmm, I thought that we don't have that issue anymore as we are doing 3 retries to upate. Maybe I should add a sleep of 1s to the retries ?

**Comment by dsimansk** [comment]
/retest

```
conversion webhook for &{map[apiVersion:serving.knative.dev/v1 kind:Service metadata:map[creationTimestamp:2020-02-17T11:16:41Z generation:1 name:svc1 namespace:kne2esmoketests uid:5082bda3-2456-4512-ba0b-43b246293519] spec:map[template:map[metadata:map[annotations:map[client.knative.dev/user-image:gcr.io/knative-samples/helloworld-go] creationTimestamp:<nil> name:svc1-tbllh-1] spec:map[containers:[map[env:[map[name:TARGET value:Knative]] image:gcr.io/knative-samples/helloworld-go name: resources:map[]]]]]]]} failed: Post https://webhook.knative-serving.svc:443/?timeout=30s: no endpoints available for service "webhook"
```

**Comment by navidshaikh** [comment]
/retest

```
        🦆 kn service create hello --image gcr.io/knative-samples/helloworld-go --namespace kne2etests8
        ┃ Creating service 'hello' in namespace 'kne2etests8':
        ┃ 
        ┃   1.617s The Route is still working to reflect the latest desired specification.
        ┃   2.029s Revision "hello-pvrmq-1" referenced in traffic not found.
        ┃ 
        🔥 RevisionMissing: Revision "hello-pvrmq-1" referenced in traffic not found.
```

@rhuss :
> Maybe I should add a sleep of 1s to the retries ?

We can try that.

**Comment by navidshaikh** [comment]
/retest

```
        traffic_split_test.go:417: assertion failed: error is not nil: expecting 2 targets, got 1 targets targets: ,echo2-rev-2,100,true separator: |
```

**Pull request merged**
