### PR TITLE
Fixes issue #111 by responding with an error for unknown subcommands

### PR DESCRIPTION
**Pull request by maximilien**
```bash
➜  client git:(issue111) ✗ ./kn service unknown
unknown command "unknown" for "kn service"
```

This works for both the `service` and `revision` groups.

### CODE REVIEW

**Comment by maximilien** [comment]
Fixes #111 

cc: @sixolet

**Comment by maximilien** [comment]
BTW, FYI, just for kicks...

I implemented this feature for the `plugin` group in #177 and also added a Ginkgo UT. 

The resulting test is so much more readable than what's here--albeit a bit longer (precisely ~25 lines more). 

However, the clarity of the test is worth noting. And it also tests all aspects of the command group cleanly. 

I am pasting here (w/o import),  so you see:

1. Go test

```go
import (
   ...
)

func fakeService(args []string, response *v1alpha1.ServiceList) (action client_testing.Action, output []string, err error) {
	knParams := &commands.KnParams{}
	cmd, fakeServing, buf := commands.CreateTestKnCommand(NewServiceCommand(knParams), knParams)
	fakeServing.AddReactor("*", "*",
		func(a client_testing.Action) (bool, runtime.Object, error) {
			action = a
			return true, response, nil
		})
	cmd.SetArgs(args)
	err = cmd.Execute()
	if err != nil {
		return
	}
	output = strings.Split(buf.String(), "\n")
	return
}

func TestUnknownSubcommand(t *testing.T) {
	_, _, err := fakeService([]string{"service", "unknown"}, &v1alpha1.ServiceList{})
	if err == nil {
		t.Error(err)
		return
	}

	if err.Error() != "unknown command \"unknown\" for \"kn service\"" {
		t.Errorf("Bad error message %s", err.Error())
	}
}
```

2. Ginkgo test

```go
import (
   ...
)

var _ = Describe("kn service", func() {
	var (
		serviceCmd *cobra.Command
		knParams  *KnParams
	)

	BeforeEach(func() {
		knParams = &KnParams{}
		serviceCmd = NewServiceCommand(knParams)
	})

	Describe("#NewServiceCommand", func() {
		It("creates a new cobra.Command", func() {
			Expect(serviceCmd).NotTo(BeNil())
			Expect(serviceCmd.Use).To(Equal("service"))
			Expect(serviceCmd.Short).To(Equal("Service command group"))
			Expect(serviceCmd.Long).To(ContainSubstring("Provides utilities for interacting with services."))
			Expect(serviceCmd.Args).NotTo(BeNil())
			Expect(serviceCmd.Run).NotTo(BeNil())
		})

		Context("called with known subcommand", func() {
			var (
				fakeExecuted bool
			)

			BeforeEach(func() {
				serviceCmd.AddCommand(&cobra.Command{
					Use:   "fake",
					Short: "fake subcommand",
					RunE: func(cmd *cobra.Command, args []string) error {
						fakeExecuted = true
						return nil
					},
				})
			})

			It("executes the subcommand RunE func", func() {
				serviceCmd.SetArgs([]string{"fake"})
				err := serviceCmd.Execute()
				Expect(err).NotTo(HaveOccurred())
				Expect(fakeExecuted).To(BeTrue())
			})
		})

		Context("called with unknown subcommand", func() {
			It("fails with 'unknown command' message", func() {
				serviceCmd.SetArgs([]string{"unknown"})
				err := serviceCmd.Execute()
				Expect(err).To(HaveOccurred())
				Expect(err.Error()).To(ContainSubstring("unknown command \"unknown\" for"))
			})
		})
	})
})
```

**Comment by navidshaikh** [comment]
```
➜  client git:(drmax-issue111) ./kn revision unkown
unknown command "unkown" for "kn revision"
```
fine! but,
```
➜  client git:(drmax-issue111) ./kn revision       
➜  client git:(drmax-issue111) echo $?
0
```

**Comment by maximilien** [comment]
> only `kn revision` should also give error/help message

I can do that. Was not sure it made sense to error, but I guess we can treat it as invalid "" command/flags.

Will update today. Thx

**Comment by maximilien** [comment]
Done @navidshaikh. Let me know what you think. Best.

**Comment by maximilien** [comment]
> Works! , but this change should also be applied to other commands as well for eg `kn version unkown` (or completion) should also prompt the error.

Well this was for group commands. I added it to the `plugin` WIP #177.

The other commands `version` and `completion` are leaf commands. I think we should discuss with group as to whether silently ignoring extra params or giving an error is warranted. 

Mainly because if the leaf command takes a param then it will deal with it naturally in the implementation of the command. If it does not, like for `version` and `completion`, then the question becomes to ignore or not.

Worth noting that `kubectl version` which is a leaf command silently ignores extra params:

```bash
kubectl version blah
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-09-29T05:56:06Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6+IKS", GitCommit:"ac5f7341d5d0ce8ea8f206ba5b030dc9e9d4cc97", GitTreeState:"clean", BuildDate:"2019-05-09T13:26:51Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sixolet** [comment]
Can we print the usage to stdout *and* make it an error?

**Comment by maximilien** [comment]
> Can we print the usage to stdout _and_ make it an error?

Do you mean for:

```bash
kn service lol
Manage your Knative building blocks:

Serving: Manage your services and release new software to them.
Build: Create builds and keep track of their results.
Eventing: Manage event subscriptions and channels. Connect up event sources.

Usage:
  kn [command]

Available Commands:
  completion  Output shell completion code (default Bash)
  help        Help about any command
  revision    Revision command group
  service     Service command group
  version     Prints the client version

Flags:
  -h, --help                help for kn
      --kubeconfig string   kubectl config file (default is $HOME/.kube/config)

Use "kn [command] --help" for more information about a command.

unknown command "lol" for "kn service"
```

For both `service` and `revision`. Confirm and I will update.

**Comment by sixolet** [comment]
> ... For both service and revision. Confirm and I will update.

Yeah, exactly 👍

**Comment by sixolet** [comment]
... actually, not exactly. Should print the equivalent for the subcommand.

**Comment by maximilien** [comment]
> ... actually, not exactly. Should print the equivalent for the subcommand.

Yup, got you. Makes sense. Will do that.

**Comment by maximilien** [comment]
OK done. Updated the commit message but worth repeating here for clarity.

```bash
➜  client git:(issue111) ✗ ./kn service unknown
Service command group

Usage:
  kn service [flags]
  kn service [command]

Available Commands:
  create      Create a service.
  delete      Delete a service.
  describe    Describe available services.
  list        List available services.
  update      Update a service.

Flags:
  -h, --help   help for service

Global Flags:
      --kubeconfig string   kubectl config file (default is $HOME/.kube/config)

Use "kn service [command] --help" for more information about a command.
unknown command "unknown" for "kn service"

➜  client git:(issue111) ✗ ./kn revision lol
Revision command group

Usage:
  kn revision [flags]
  kn revision [command]

Available Commands:
  describe    Describe revisions.
  list        List available revisions.

Flags:
  -h, --help   help for revision

Global Flags:
      --kubeconfig string   kubectl config file (default is $HOME/.kube/config)

Use "kn revision [command] --help" for more information about a command.
unknown command "lol" for "kn revision"
```

This works for both the `service` and `revision` groups whe called with empty and unknown sub-command.

Note also that the tests do not check for the usage output. Complicated to do with our current UT framework. Will update that when #161 is done and we start moving to Ginkgo. I'll have an example in #177 for `plugin` group.

**Comment by maximilien** [comment]
OK so `pull-knative-client-build-tests` is failing with:

```
2019/06/20 22:25:45 Error creating license classifier: cannot register licenses: EOF
```

Not clear why. I've checked header files for licenses and our own `./build.sh` does that. Dependencies are updated and all UTs and e2e locals are running fine. 

Perhaps this is infra or intermittent. Trying again one more time today:

/test pull-knative-client-build-tests

**Comment by rhuss** [comment]
@maximilien you can reproduce the error locally with 

```
go install github.com/knative/test-infra/tools/dep-collector
dep-collector -check $(go list ./...)
```

(btw, I could add this to the build script, too, when checking for licenses). 

For me this doesn't yield any error, though, so it looks a bit like a flake for me. Let's retest it again.

**Comment by cppforlife** [comment]
can this be done more generically so that it applies to all grouped commands? i dont think this is manageable as other groups are added.

**Comment by maximilien** [comment]
> can this be done more generically so that it applies to all grouped commands? i dont think this is manageable as other groups are added.

It’s two lines in the `RunE` of the group definition. Not clear could save more by moving to a common function. Short of adding feature in `Cobra` I don’t see a generic option. I suggest we explore this when next group is added.

**Comment by cppforlife** [comment]
i think this could be implemented more generically by _visiting_ commands and their children. when we find command without RunE specified and if it has children we should set that to the function that we've manually added to the service cmd.

**Comment by maximilien** [comment]
> i think this could be implemented more generically by _visiting_ commands and their children. when we find command without RunE specified and if it has children we should set that to the function that we've manually added to the service cmd.

Not sure the added complexity is worth it really, but easy enough to do. I’ll wait to see if others chime in.

**Comment by rhuss** [comment]
> Not sure the added complexity is worth it really. Especially since we don’t have a lot of command group and had the pace we are going, doubtful we add two or three more by EOY. But easy enough to do, it’s just a tree search from the root.

Just as info, there will be quite more command groups when we introduce eventing. I'm currently writing on a proposal for how to integrate eventing (talked with some eventing guys), and alone eventing probably will add 5 or 6 groups (broker, channel, importer, trigger, sequence, ..)

My plan is to finish this document over the weekend so that we might discuss this on the WG meeting as it also has an overlap with our plugin discussion (as channels and importers also need a kind of plugin architecture albeit more 'typed', e.g. with a contract)

**Comment by maximilien** [comment]
> > Not sure the added complexity is worth it really. Especially since we don’t have a lot of command group and had the pace we are going, doubtful we add two or three more by EOY. But easy enough to do, it’s just a tree search from the root.
> 
> Just as info, there will be quite more command groups when we introduce eventing. I'm currently writing on a proposal for how to integrate eventing (talked with some eventing guys), and alone eventing probably will add 5 or 6 groups (broker, channel, importer, trigger, sequence, ..)
> 
> My plan is to finish this document over the weekend so that we might discuss this on the WG meeting as it also has an overlap with our plugin discussion (as channels and importers also need a kind of plugin architecture albeit more 'typed', e.g. with a contract)

OK fair enough. Implementing the generic version now.

----
WRT to eventing commands. There is also an IBM team that have looked into this and have a proposal in the works. Let me cc: them here, perhaps we can all jump to a common eventing issue? Can't see any open, so I created this issue #217 to coalesce the various discussions on eventing.

**Comment by rhuss** [comment]
@maximilien you probably rebase and squash your commits as this PR currently involves also commits from other contributors (thats probably the reason why the CLA check fails).

**Comment by maximilien** [comment]
OK since the new code is vastly different from this one. I am closing this PR. We will still have the good discussions but can use new up coming PR for new discussion on the new more general PR.

**Comment by maximilien** [comment]
See #218

**Pull request closed without merging**
