### PR TITLE
Calculate traffic split when N-1 revisions are specified

### PR DESCRIPTION
**Pull request by vyasgun**
## Changes

* Determine traffic split when N-1 revisions are specified
* In case `@latest` is specified, cannot determine the split unless it sums to 100

## Reference

Fixes #

### CODE REVIEW

**Comment by vyasgun** [comment]
thanks, @dsimansk!

**Comment by dsimansk** [comment]
Since all the review comments are addressed, lets get it in. :)

Thanks!
/approve
/lgtm

**Pull request merged**
