### PR TITLE
fix typo in source list-types examples

### PR DESCRIPTION
**Pull request by navidshaikh**
Update other list command examples as well.

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

```
        🔥 RevisionMissing: Revision "hello-yslwp-1" referenced in traffic not found.
```

**Comment by rhuss** [comment]
/retest 

This flake should eventuall fixed when the 'sync delete' PR lands.

**Comment by navidshaikh** [comment]
> This flake should eventuall fixed when the 'sync delete' PR lands.

yes, and we'll need synced revision delete as well next.
/cc: @dsimansk

**Pull request merged**
