### PR TITLE
chore: Update testing infrastructure

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by navidshaikh** [comment]
The e2e actually [passed](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/488/pull-knative-client-integration-tests/1192424445520646144#1:build-log.txt%3A1481) and then `Something went wrong: encountered 1 errors: [error during /tmp/kubernetes.qobw2wgiNx/e2e-test.sh: exit status 1]`
/test pull-knative-client-integration-tests

**Comment by rhuss** [comment]
I think it was a timeout issue. 🤞 that its a hick-up

**Pull request merged**
