### PR TITLE
v0.16.1 release backports

### PR DESCRIPTION
**Pull request by navidshaikh**
## Description
Client v0.16.1 release backports for bug fixes.

## Changes
- Update CHANGELOG
- Cherry pick:
  - #980 
  - #975 
  - #971 
  - #966 
  - #963 
  - #951 
  - #948 
  - #934

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

      result_collector.go:75: ERROR: Error: ReconcileIngressFailed: Ingress reconciliation failed

**Comment by hemanrnjn** [comment]
@googlebot I consent.

**Comment by navidshaikh** [comment]
@gosoon : Can you please comment `@googlebot I consent.` here to get the cla check happy?

**Comment by Kaustubh-pande** [comment]
@googlebot I consent.

**Comment by cardil** [comment]
@googlebot I consent.

**Comment by gosoon** [comment]
@googlebot I consent.

**Pull request merged**
