### PR TITLE
Adds human-friendly table printing for resource listing

### LINKED ISSUE #84: Add human friendly printer for resource listing
We'll need a human-friendly printer for resource listing along with all the printers from genericclioptions https://godoc.org/k8s.io/cli-runtime/pkg/genericclioptions .

For eg: As its done in kube https://github.com/kubernetes/kubernetes/tree/master/pkg/printers

### PR DESCRIPTION
**Pull request by navidshaikh**
Fixes #84 
All the credits goes to https://github.com/kubernetes/kubernetes/tree/master/pkg/printers

### CODE REVIEW

**Comment by cppforlife** [comment]
@navidshaikh i dont see any command using this printers, or did i miss it?

**Comment by navidshaikh** [comment]
> @navidshaikh i dont see any command using this printers, or did i miss it?

@cppforlife : I'll raise separate PRs for commands using this printer.

**Comment by navidshaikh** [comment]
@cppforlife Here is the new one https://github.com/knative/client/pull/90 rebased onto this PR.

**Pull request merged**
