### PR TITLE
Remove deprecated --inject-broker flag from trigger cmds

### LINKED ISSUE #1846: Remove deprecated `--inject-broker` flag from `trigger` cmds
Per title and code comment remove the deprecated code.

https://github.com/knative/client/blob/8dc8a9f26c1925633def9e58f063ba701cbf4736/pkg/kn/commands/trigger/update_flags.go#L54-L60

### PR DESCRIPTION
**Pull request by xiangpingjiang**
## Changes

* remove deprecated --inject-broker flag
* remove related test

## Reference

Fixes #1846 

**Release Note**

```release-note
Remove deprecated `--inject-broker` flag from `kn trigger` cmd group
```

### CODE REVIEW

**Comment by dsimansk** [comment]
The failing E2E are unrelated to this PR, see #1854.

**Comment by xiangpingjiang** [comment]
> The failing E2E are unrelated to this PR, see #1854.

@dsimansk 

Thanks, I will try to fix it.

**Comment by xiangpingjiang** [comment]
@dsimansk  all tests passed, now can we merge this pr?

**Comment by dsimansk** [comment]
> @dsimansk all tests passed, now can we merge this pr?

Sure, and once againg thanks for fixing the deprecated API on the way. Greatly appreciated!

/approve
/lgtm

**Pull request merged**
