### PR TITLE
Adding support for darwin/arm64

### LINKED ISSUE #1394: Support darwin/arm64 for the new generation of Apple Hardware (Apple Silicon)
### Feature request

Create arm64 binaries for macOs (`darwin/arm64`)

### Use case

While the newer M1 Macs can still work with `darwin/amd64`, it makes sense to already support the newer architecture for kn as well.

/kind good-first-issue

### PR DESCRIPTION
**Pull request by vyasgun**
## Description

Adding cross compile support for darwin/arm64

## Changes

* Added OS and Arch arguments to go build in cross compile routine of the build script

## Reference

Fixes #1394

### CODE REVIEW

**Comment by dsimansk** [comment]
Thanks, looks good just 2 points to fix please:
- Add arm64 to release script as well: https://github.com/knative/client/blob/main/hack/release.sh#L36-L37
- Add changelog entry

**Comment by dsimansk** [comment]
@vyasgun does the `./hack/build.sh -x` works for you locally?

**Comment by dsimansk** [comment]
There's something shady happening on `go 1.15.12`, but works fine on `1.16.x`.

```
➜  client git:(pr/arm64) ✗ gvm use go1.15.12  
Now using version go1.15.12
➜  client git:(pr/arm64) ✗ ./hack/build.sh -x
⚔️ Compile
   🐧 kn-linux-amd64
   💪 kn-linux-arm64
   🍏 kn-darwin-amd64
   🍎 kn-darwin-arm64
# knative.dev/client/cmd/kn
/home/dsimansk/.gvm/gos/go1.15.12/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-913066744/go.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status

   🎠 kn-windows-amd64.exe
   Z  kn-linux-s390x
   P  kn-linux-ppc64le
✋ Cross platform build failed
➜  client git:(pr/arm64) ✗ go version                            
go version go1.15.12 linux/amd64
```

**Comment by dsimansk** [comment]
@vyasgun can you please try to update go version in `go.mod` to `1.16`, to verify if build test passes.

**Comment by rhuss** [comment]
+1 for upgrading to go 1.16

**Comment by vyasgun** [comment]
the go version on my machine is 1.16.5. I'll change and verify in go.mod.

**Comment by dsimansk** [comment]
Thanks @vyasgun!
/lgtm

**Review by maximilien — APPROVED** [review]
Interesting that the proprietary hardware is a red apple :)

/ok-to-test
/approve
/lgtm

**Pull request merged**
