### PR TITLE
chore(changelog): Add a changelog

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by cppforlife** [comment]
@rhuss what's the rationale for having this file? is it for devs or end users?

**Comment by rhuss** [comment]
> @rhuss what's the rationale for having this file? is it for devs or end users?

end users, a curated list which is growing while going and not as an afterthought when doing a release.

**Comment by rhuss** [comment]
the format of this changelog is kind of experimental, happy to revert it to a more conventional (bullet list like) format.

**Comment by sixolet** [comment]
/lgtm
I like emoji

**Pull request merged**
