### PR TITLE
Add dependencies to Eventing 0.10.0

### PR DESCRIPTION
**Pull request by daisy-ycguo**
## Proposed Changes

* Add dependencies to Eventing v0.10.0

### CODE REVIEW

**Comment by maximilien** [comment]
Seems like you need to rebase @daisy-ycguo

**Comment by daisy-ycguo** [comment]
@rhuss and @maximilien It's ready for review now. Thank you.

**Comment by rhuss** [comment]
/hold

Let's wait until 0.10.0 has landed, then we have 6 weeks to ramp up eventing for 0.11.0

**Comment by rhuss** [comment]
@daisy-ycguo this PR looks good to me, but needs a rebase and conflict resolution. Happy to merge tomorrow when the conflict is resolved.

**Pull request merged**
