### PR TITLE
Run latest e2e job against serving 0.17.3 and eventing 0.17.4

### PR DESCRIPTION
**Pull request by navidshaikh**
test against the latest patch releases

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

    7.662s Ingress has not yet been reconciled.
    Error: timeout: service 'hello' not ready after 600 seconds

**Comment by navidshaikh** [comment]
/retest

consistently failing in smoke tests with same error :thinking: 
 ```
 Error: timeout: service 'hello' not ready after 600 seconds
 ```

**Comment by navidshaikh** [comment]
/retest


     9.103s Ingress has not yet been reconciled.
     Error: timeout: service 'hello' not ready after 600 seconds

**Comment by dsimansk** [comment]
@navidshaikh early fail on the smoke tests seems to be a new flake?

/retest

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

It would be nice if we could pick these up automatically.

**Comment by navidshaikh** [comment]
failing net-istio setup [log](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1018/pull-knative-client-integration-tests-latest-release/1308762519682158594#1:build-log.txt%3A253) causing the service to not become ready
```
Installing net-istio components from https://storage.googleapis.com/knative-releases/net-istio/previous/v0.17.3/net-istio.yaml
error: unable to read URL "https://storage.googleapis.com/knative-releases/net-istio/previous/v0.17.3/net-istio.yaml", server reported 404 Not Found, status code=404
```
we're using 0.17.3 patch release of serving, the test-infra scripts uses same version for net-istio it seems, but cant find it
cc: @nak3

**Comment by nak3** [comment]
Yeah, serving uses our own script as:

https://github.com/knative/serving/blob/133c4118c3b7c71119ab88ccc54f85243c69b0ae/test/e2e-common.sh#L185
(and download the latest net-istio,yaml)
https://github.com/knative/serving/blob/133c4118c3b7c71119ab88ccc54f85243c69b0ae/test/e2e-common.sh#L242-L249

I think serving's script should be donated to [test-infra](https://github.com/knative/test-infra/blob/master/scripts/library.sh) and use it commonly.
/cc @chizhg @coryrc

**Comment by rhuss** [comment]
@navidshaikh how should we proceed with this PR ?
@navidshaikh if you say donate, should we create a PR for the test-infra ?

**Comment by nsk-magassian** [comment]
/close

done by #1036

**Pull request closed without merging**
