### PR TITLE
fix lint errors

### PR DESCRIPTION
**Pull request by toshi0607**
Fixes #

no issues

## Proposed Changes

fix lints based on
* misspell
* ineffassign
* golint

https://goreportcard.com/report/github.com/knative/client

**Release Note**

```release-note
-
```

### CODE REVIEW

**Comment by toVersus** [comment]
Please fix this as well?

https://github.com/knative/client/blob/3995f68b54fddca4e5916aafb8a910cc50deeb64/pkg/kn/core/root.go#L132

**Comment by toshi0607** [comment]
@toVersus Thank you! fixed!

**Pull request merged**
