### PR TITLE
chore: Update version command for release v0.18.0

### PR DESCRIPTION
**Pull request by navidshaikh**
## Description
Mention serving/eventing vendor version v0.18.0

### CODE REVIEW

**Review by maximilien — CHANGES_REQUESTED** [review]
/lgtm 
/retest

**Comment by navidshaikh** [comment]
/retest


eventing setup flake

**Comment by rhuss** [comment]
hmm, the integration test issue doesn't seems to be a flake.

@matzew has there been any change recently in eventing ? We have issues during setup that eventing doesn't starts up properly:

```
customresourcedefinition.apiextensions.k8s.io/inmemorychannels.messaging.knative.dev unchanged
deployment.apps/imc-controller created
deployment.apps/imc-dispatcher created
Waiting until all pods in namespace knative-eventing are up......................................................................................................................................................
ERROR: timeout waiting for pods to come up
eventing-controller-6fc9c6cfc4-8n5j5    1/1   Running   0     5m34s
eventing-webhook-667c8f6dc4-g88wx       0/1   Running   6     5m34s
imc-controller-6c4f87765c-np6mw         1/1   Running   0     5m23s
imc-dispatcher-74dcf4647f-cqjtk         1/1   Running   0     5m23s
mt-broker-controller-6d789b944d-h68dd   1/1   Running   0     5m24s
skipped 352 lines unfold_more
---- Thu Oct  1 16:04:56 PDT 2020
----------------------------------:-------------------------------
deployment.apps/sugar-controller created
Waiting until all pods in namespace knative-eventing are up......................................................................................................................................................
ERROR: timeout waiting for pods to come up
eventing-controller-6fc9c6cfc4-8n5j5    1/1   Running            0     10m
eventing-webhook-667c8f6dc4-g88wx       0/1   CrashLoopBackOff   7     10m
imc-controller-6c4f87765c-np6mw         1/1   Running            0     10m
imc-dispatcher-74dcf4647f-cqjtk         1/1   Running            0     10m
mt-broker-controller-6d789b944d-h68dd   1/1   Running            0     10m
skipped 345 lines unfold_more
2020/10/01 23:08:19 http: TLS handshake error from 10.24.0.1:59356: server key missing
2020/10/01 23:08:20 http: TLS handshake error from 10.24.0.1:59366: server key missing
2020/10/01 23:08:21 http: TLS handshake error from 10.24.0.1:59374: server key missing
2020/10/01 23:08:22 http: TLS handshake error from 10.24.0.1:59384: server key missing
2020/10/01 23:08:23 http: TLS handshake error from 10.24.0.1:59394: server key missing
ERROR: Knative setup failed
```

**Comment by navidshaikh** [comment]
/retest

looks like we're hitting https://github.com/knative/eventing/issues/4165 which is merged yesterday in master and needs to backported to v0.18 ?

**Pull request merged**
