### PR TITLE
e2e: Dump stdout and describe ksvc

### PR DESCRIPTION
**Pull request by navidshaikh**
/hold

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

ERROR: timeout waiting for pods to come up

**Comment by rhuss** [comment]
@navidshaikh I think we can merged this PR regardless of we can catch the flake now. Shouldn't harm to have that extra output in case of an error ?

**Comment by navidshaikh** [comment]
@rhuss : would like to see once if its printing the required info before merging;

**Comment by navidshaikh** [comment]
note the timeout error but another one, though it shows the stdout dump and ksvc describe in logs now:
https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/659/pull-knative-client-integration-tests/1227550120803831808#1:build-log.txt%3A811

**Comment by rhuss** [comment]
It's crazy, the test dont want to fail anymore ....

/retest

**Comment by navidshaikh** [comment]
@rhuss :

Error:
```
Failed to successfully execute 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests9': Execution error: stderr: 'timeout: service 'hello' not ready after 600 seconds
```
and 
```
  Warning  InternalError  10m                service-controller  service: "hello" does not own configuration: "hello"
```
ref: [logs](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/659/pull-knative-client-integration-tests/1227593662116925447#1:build-log.txt%3A872)

**Pull request merged**
