### PR TITLE
Pin serving and eventing to release-0.18

### PR DESCRIPTION
**Pull request by ZhiminXiang**
/assign @mattmoor 
/assign @n3wscott

### CODE REVIEW

**Comment by ZhiminXiang** [comment]
The issue looks like similar with https://github.com/knative/eventing/issues/4165

Let me have another try.

/test pull-knative-client-integration-tests

**Comment by ZhiminXiang** [comment]
This time the `TestServiceOptions` test failed. Looks like this test is flaky https://testgrid.knative.dev/client#continuous.

/test pull-knative-client-integration-tests

**Comment by ZhiminXiang** [comment]
@rhuss could you help to investigate this PR?

**Review by navidshaikh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
