### PR TITLE
bump to k8s 1.18

### PR DESCRIPTION
**Pull request by MIBc**
## Description
bump to k8s 1.18

## Changes
* Bump deps to k8s 1.18.8
* Add context.Context argument in clientsets(both serving and eventing), dynamic client.
* Update knative/pkg, knative/serving, knative/eventing dependencies.

releated issue: #1009

### CODE REVIEW

**Comment by rhuss** [comment]
Awesome, thanks ! Looks like that there are some issues with the tests. 'hope for a review soon

**Comment by MIBc** [comment]
I will fix them asap.

**Review by maximilien — APPROVED** [review]
/ok-to-test

**Comment by navidshaikh** [comment]
/retest


        result_collector.go:75: ERROR: Error: ReconcileIngressFailed: Ingress reconciliation failed

**Comment by MIBc** [comment]
@rhuss  Please review.

**Comment by navidshaikh** [comment]
/close

This is taken care in https://github.com/knative/client/pull/1025 , closing the PR!
Thanks @MIBc!

**Pull request closed without merging**
