### PR TITLE
Update test-infra to pick up the fix

### LINKED ISSUE #758: dot release failing with git checkout error
First dot release of the client 0.13.1 failing while checking out release branch

excerpts:
```
From https://github.com/knative/client
 * [new branch]      release-0.13 -> upstream/release-0.13
warning: refname 'upstream/release-0.13' is ambiguous.
Version v0.13.0 is at commit db569fae177eb41d688399c33f2d9de64875568f
Branch release-0.13 is at commit 6e3fac0ab74b9d50b62d9810b95162d26761dd2f
Will create release 0.13.1 at commit 6e3fac0ab74b9d50b62d9810b95162d26761dd2f
Release notes from v0.13.0 copied to /tmp/tmp.N9i4JVR28R
Remote upstream URL is 'https://github.com/knative/client'
error: Your local changes to the following files would be overwritten by checkout:
	go.mod
	go.sum
Please commit your changes or stash them before you switch branches.
Aborting
error: cannot checkout branch release-0.13
```
https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-client-dot-release/1242452798725951488#1:build-log.txt%3A61

/cc @chizhg @chaodaiG

### PR DESCRIPTION
**Pull request by chizhg**
## Changes

* Update test-infra latest changes to fix https://github.com/knative/client/issues/758

## Reference

Fixes #758 

/cc @rhuss 
/cc @navidshaikh

### CODE REVIEW

**Comment by navidshaikh** [comment]
@chizhg : The changeset should be against release-0.13 branch ?

**Comment by chizhg** [comment]
> @chizhg : PR should be against release-0.13 branch ?

No, it needs to be against master, as we run dot-release for the latest release branch from master branch.

**Comment by navidshaikh** [comment]
@chizhg : Alright! Can you please trigger the dot release job? Thanks!

**Comment by chizhg** [comment]
> @chizhg : Alright! Can you please trigger the dot release job? Thanks!

Triggered ! https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-client-dot-release/1242541126099931136

**Pull request merged**
