### PR TITLE
Add a Makefile

### PR DESCRIPTION
**Pull request by cdrage**
Adds a makefile for standard procedures such as creating the binary +
running tests.

### CODE REVIEW

**Comment by sixolet** [comment]
I'd prefer not to include a makefile unless we need something more complicated than a `go build` to build it, or a `go test` to test it.

Other opinions?

**Comment by sixolet** [comment]
Hum. Tests are passing for me. Anyway, we should get CI testing up in this repo.

**Comment by cdrage** [comment]
@sixolet Just opened up issue #23 with regards to tests..

**Comment by cppforlife** [comment]
@cdrage how about just adding bash script such as `hack/build.sh` and `hack/test.sh`

**Pull request closed without merging**
