### PR TITLE
Update modules and dependencies to knative 0.5

### LINKED ISSUE #67: Update to knative-serving 0.4.0 as dependency
Currently, the client's dependency on knative serving is still 0.3.0 in `go.mod`.

### PR DESCRIPTION
**Pull request by sixolet**
Fixes #67

### CODE REVIEW

**Comment by sixolet** [comment]
Needed to manually pin go-cmp, since knative/pkg used a feature of it that wasn't released in 0.2, which is the most recent release

**Comment by rhuss** [comment]
Can we please get rid of `cloud.google.com/go v0.34.0` dependency as in #68 ? Also, I believe the dependency list in go.mod can be much smaller (38 in #68 compared to 56 deps here). 

Is there a particular reason why #68 can't be modified to pin go-cmp as required ?

**Comment by cppforlife** [comment]
+1 for what @rhuss said

**Comment by rhuss** [comment]
I suggest closing this PR as #68 has been merged and potentially open a new one with a fix to pin go-cmp if this is still needed.

**Comment by matzew** [comment]
@sixolet hey Naomi, mind to rebase this ?   Otherwise `/lgtm` ;-)

**Pull request closed without merging**
