### PR TITLE
Enable unparam linter and fix issues

### PR DESCRIPTION
**Pull request by markusthoemmes**
## Description

Probably the linter that found the most bugs over in Serving. Think of it as a more aggressive deadcode linter, telling you about unused parameters and unused return types.

Tests are excluded as the noise ratio is much higher in them.

/assign @rhuss

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
/ok-to-test
/lgtm
Thanks for this. Did not realize so many unnecessary params. Thx

**Comment by rhuss** [comment]
Looks like we have issues in the integration test to the cluster up

/retest

**Pull request merged**
