### PR TITLE
client release v0.20.0 prep

### PR DESCRIPTION
**Pull request by navidshaikh**
## Description

Release prep for client v0.20.0 following serving and eventing.

## Changes
* Serving and Eventing deps at v0.20.0
* k8s deps at v0.18.12 
* Update `kn version` command
* Run e2e tests against v0.20.0 of serving/eventing
* Update CHANGELOG with release date as Jan 14

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by navidshaikh** [comment]
sugar controller yaml url needs a fix

```error: unable to read URL "https://storage.googleapis.com/knative-releases/eventing/previous/v0.12.0/eventing-sugar-controller.yaml", server reported 404 Not Found, status code=404
```

**Review by rhuss — APPROVED** [review]
looks good to me. Thanks !

/lgtm

**Pull request merged**
