### PR TITLE
Fix resource listing with -oname flag

### LINKED ISSUE #798: Fix resource listing with -oname flag
### Bug report

Follow up issue of https://github.com/knative/client/issues/754 for fixing this for other resource listing.

### Expected behavior

`-oname` flag works for all resource listing.

### Steps to reproduce the problem

```
kn revision list -oname
```

### kn version
HEAD

### Knative (serving/eventing) version
Any

Fix for service listing: https://github.com/knative/client/pull/775

### PR DESCRIPTION
**Pull request by daisy-ycguo**
## Description

Follow up PR #775  to fix other resources `list -oname` issue.

## Changes

* Fix errors of resource list command to support -oname flag

## Reference

Fixes #798

### CODE REVIEW

**Comment by rhuss** [comment]
> @navidshaikh: The label(s) `/label backport/candidate` cannot be applied. These labels are supported: `proposal/0.11, proposal/0.12, proposal/0.13, proposal/0.14, proposal/0.15, proposal/0.16, proposal/0.17, proposal/0.18, proposal/0.19, channel/kafka, channel/natss, source/awssqs, source/camel, source/ceph, source/couchdb, source/github, source/kafka, source/prometheus`

Looks like we "inherited" some configuration from eventing // cc: @chizhg 

@navidshaikh in the meantime you can add the label via the GitHub UI.

**Comment by daisy-ycguo** [comment]
> Looks good on a first glance.
> 
> Would it be possible to add a test ?

will add tests soon.

**Comment by rhuss** [comment]
@daisy-ycguo there is a compile error:

```
test/e2e/source_apiserver_test.go:98:42: cannot use apiserverSources (type []string) as type string in argument to util.ContainsAll
```

**Pull request merged**
