### PR TITLE
Add linting config and fix issues.

### PR DESCRIPTION
**Pull request by markusthoemmes**
## Description

As per title. Prep work to roll out golangci-lint actions across the board.

## Changes

* Removed unused code.
* Simplified expressions.
* Made structs explicitly specified.

/assign @rhuss

### CODE REVIEW

**Comment by markusthoemmes** [comment]
These seem to be common flakes via testgrid

/retest

**Review by maximilien — COMMENTED** [review]
Cool. Many of the changes are straightforward. Some removing “unused” code are kind of scary... but assuming tests passing I guess that’s a good thing to do. 

Worried a bit about a few changes in `lib/*` and `pkg/*` some of these are externally used packages so might not be good to change as might break things. Thinking of plugins. 

Also, not 100% clear if this listing tool already takes care of not removing code that impacts public interfaces, since some of the changes are in private fields - so implementation details. I’ll cc some plugin authors and ask them to verify.

Cc: @daisy-ycguo @zhanggbj @zhangtbj see last paragraph ^^^

Also, not clear what’s causing your test failure. Could be flake.

/retest

**Comment by markusthoemmes** [comment]
None of it should be impacting behavior/interfaces I believe. I leaves exported fields/functions/constants etc. alone completely.

**Comment by navidshaikh** [comment]
not a flake but hitting bug #1002 here

**Comment by navidshaikh** [comment]
@markusthoemmes : e2e test failure is fixed, and this should pass now, can you please rebase?

**Comment by markusthoemmes** [comment]
Rebased!

**Review by navidshaikh — APPROVED** [review]
/lgtm
/approve

**Comment by navidshaikh** [comment]
/retest

```
     result_collector.go:75: ERROR: Error: ReconcileIngressFailed: Ingress reconciliation failed
```
flake

**Comment by dsimansk** [comment]
/retest
same flake

**Pull request merged**
