### PR TITLE
Use Tekton Catalog GA structure for tasks

### LINKED ISSUE #965: Tekton tests should use new Tekton catalog structure
### Bug report

Knative client e2e tests that focus on Tekton integration should use tasks that are described with new Tekton Catalog structure.

### Expected behavior

Tekton tests should be able to work with tasks that are defined in new Tekton Catalog structure.

### Steps to reproduce the problem

Run e2e tests for Tekton.

### Knative (serving/eventing) version

Nightly

### PR DESCRIPTION
**Pull request by cardil**
## Description

This PR changes the address for Tekton tasks, to point to the new structure. This should be done to assure we're supporting the newest definitions from Tekton catalog.

## Changes

* Use Tekton Catalog GA structure for tasks

## Reference

Fixes #965

### CODE REVIEW

**Comment by maximilien** [comment]
Also @cardil please address your 'cla/google' issue. You might need to sign or confirm something.

Thanks for the contribution.

**Comment by cardil** [comment]
> Is "0.1" the latest version, so that we will need to update for each? If true, any way to deal with this in a more dynamic fashion?

I think `0.1` is the only version for now for any task in that catalog.

**Comment by cardil** [comment]
/unhold 

https://github.com/knative/client/pull/966/commits/61edc8c5f1e36e50b8d140996be474136f50337b has been removed.

**Pull request merged**
