### PR TITLE
Refactor waiting loop to use resourceVersion

### LINKED ISSUE #1287: Refactor watch functions to pass resourceVersion
Let me add a few thoughts after digging into watch API a bit.
> 2. The CPU is pegged
> 3. `time.After` creates a new timer on each invocation. The timers aren't garbage collected until they expire, resulting in a crippling memory leak.

That's a neat fix. Thanks for pointing that out. The go docs are pretty clear there.

>     1. The code retries even though the results channel is never recreated, meaning the wait will never succeed

Indeed you're correct here as well. With the fix for watcher [race condition](https://github.com/knative/client/commit/83b8635d85c528f4da86c95ef5c3d74aa8543a30#diff-2a2da1f17418a3a96fbb5303e3406e5ae60f72536097b23d56f7ab583456ac8a) we actually lost the ability to recreate the watcher.
Even though the wait loop checks for `!ok` channel and it's the only [place](https://github.com/knative/client/blob/main/pkg/wait/wait_for_ready.go#L165-L167) producing retry=true, it's ineffective without remove initialization code.

https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes
>When retrieving a collection of resources (either namespace or cluster scoped), the response from the server will contain a resourceVersion value that can be used to initiate a watch against the server. The server will return all changes (creates, deletes, and updates) that occur after the supplied resourceVersion. This allows a client to fetch the current state and then watch for changes without missing any updates. 

As pointed out by @markusthoemmes, the `resourceVersion` can be used to avoid races like that, see the k8s docs above.

Therefore I think the right fix for the race condition is to leverage resourceVersion in our watch request. I've done a bit of testing and it seems to behave as expected, even with synthetic timeout postponing the watcher creation the events are lost. That'd make room to bring back the correct retry behaviour when channel is closed. As an good exampple and inspiration client-go's [retrywatcher](https://github.com/kubernetes/client-go/blob/master/tools/watch/retrywatcher.go) is done the same way.

_Originally posted by @dsimansk in https://github.com/knative/client/issues/1263#issuecomment-802225259_

### PR DESCRIPTION
**Pull request by dsimansk**
## Description

@rhuss per our conversation opening the PR with refactor of waiting loop. It was reverted before `0.23` release due to unstable tests probably cause by the changes.
https://github.com/knative/client/pull/1321

## Changes

* Refactor waiting loop to use resourceVersion

## Reference

Fixes #1287

### CODE REVIEW

**Review by maximilien — COMMENTED** [review]
Ping me when you are ready for a second pair of eyes review on this. Best.

**Comment by rhuss** [comment]
@dsimansk any idea how we should proceed with this PR ? Do you remember the original error that we have observed ? Doesn't look like that it occurs very often ...

**Comment by rhuss** [comment]
We decided in the WG call that we want to merge this or after the release, and then have 6 week time to detect and fix any potential issues that only occurred once in the past (not sure anymore whether this was a flake)

**Review by rhuss — COMMENTED** [review]
Thanks !

Let's get the merged back in and watch the nightly builds

/lgtm
/approve

**Pull request merged**
