### PR TITLE
feature(serving): Update API to serving.knative.dev/v1

### PR DESCRIPTION
**Pull request by rhuss**
Due to an issue with 0.12.0 (a missing constant) the update also includes an update
to the latest knative-serving  and knative-eventing dependencies from master
(as reflected in version.go)

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

```
Failed to successfully execute 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests3': Execution error: stderr: 'RevisionMissing: Revision "hello-lvkcn-1" referenced in traffic not found.
```

**Comment by rhuss** [comment]
> Failed to successfully execute 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests3': Execution error: stderr: 'RevisionMissing: Revision "hello-lvkcn-1" referenced in traffic not found.

@navidshaikh any idea how we could fix that ? For me it looks like a backend race condition within serving though. We would need to isolate the test (e.g. the concrete backend calls) and then pen an issue  in serving.

**Comment by rhuss** [comment]
@navidshaikh tests are green now, not sure how to review this beast best though ;-)

**Comment by navidshaikh** [comment]
@rhuss: We've been seeing this failure only against serving v0.12.0, didnt notice any against serving nightly though. Raised https://github.com/knative/client/pull/641 to see we this occurs against serving v0.12.1.

**Pull request merged**
