### PR TITLE
Prevent service-specific labels from being put on the revision template

### PR DESCRIPTION
**Pull request by duglin**
See: https://github.com/knative/serving/pull/6865

Signed-off-by: Doug Davis <dug@us.ibm.com>

/lint

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks for the PR and this fix is a quick fix for this issue, but does not solve the underlying issue that we already discussed while implementing labels: How can a user specify to which object to apply the label ? The service or the template ? For now its both, but there are situation (like this) where we definitely want a more fine grained resolution.

So I'm +1 for this if we fix the other issue (like using `--label` for both , `--label-service` for only the service and `--label-pod` for the pod template. same for annotations.), too and then remove that workaround (because then the use can specify this on her own).

For this very specific label we will have direct support, too, so I don't think people will provided that as label anyway.

How does this sound ?

**Comment by duglin** [comment]
Do we know when https://github.com/knative/client/pull/629 will be merged? It seems to be taking a while and this is kind of a blocker for us. I'm ok with removing this one #629 is merged.

**Comment by rhuss** [comment]
@navid, that's a question to you --^ :)

**Comment by duglin** [comment]
Let me ask this... if we did the split label feature you mentioned... would we still want code to skip "known" labels that don't belong on Revisions if the user used `--label` ?  Might be good, dunno

**Comment by duglin** [comment]
thanks @rhuss

**Pull request merged**
