### PR TITLE
Add a Makefile

### PR DESCRIPTION
**Pull request by duglin**
Just to make it a little easier for folks.

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
CI failure seems unrelated

**Comment by cppforlife** [comment]
@duglin we already have `./hack/build.sh`

**Comment by duglin** [comment]
yea but that's hidden

**Comment by duglin** [comment]
If you guys don't want a Makefile then I can modify the PR to at least add something to the main READ to point people to the current build script.  Just let me know....   it's just that right now it's not clear to newbies how to build it (i've heard complaints)

**Comment by cdrage** [comment]
Hey @duglin I agree that this makes it easier.. there's currently no documentation on how to build `kn`.

I previously opened up a PR here: https://github.com/knative/client/pull/22 but it wasn't accepted.

I suggest that we add documentation at least as well as `hack/build.sh` scripts or something a long those lines..

**Comment by cppforlife** [comment]
+1 on docs.

**Comment by navidshaikh** [comment]
Although the build steps are in DEVELOPMENT.md https://github.com/knative/client/blob/master/DEVELOPMENT.md#building-knative-client , it doesn't link the `hack/build.sh`.

**Comment by sixolet** [comment]
I think I prefer adding a quick "how to build" section to README.md

**Comment by duglin** [comment]
ok updates to docs have been made.  PTAL

**Pull request merged**
