### PR TITLE
Add SilenceUsage option to cobra command

### PR DESCRIPTION
**Pull request by nak3**
This patch adds `cmd.SilenceUsage` to command to stop usage output
after command validation.

Fixes https://github.com/knative/client/issues/38

### CODE REVIEW

**Comment by nak3** [comment]
Perhaps the command func should have `Validate()` part in the future.

**Comment by cppforlife** [comment]
@nak3 do we have to do it after validation?

**Comment by nak3** [comment]
@cppforlife sorry, I think I did not understand your question. But do you mean `cmd.SilenceUsage` should be `before` the validation rather than `after`?

**Comment by cppforlife** [comment]
@nak3 in knctl for example i set `SilenceUsage: true` on the root cmd (https://github.com/cppforlife/knctl/blob/3bcefbe5af3f809ecf5c1b04db9d5129b80e5984/pkg/knctl/cmd/knctl.go#L75). i m wondering if we can consolidate this configuration instead of placing it in all commands?

**Comment by nak3** [comment]
@cppforlife I see. Yes, agree. Consolidating it insead of placing it in all commands is better.

**Pull request merged**
