### PR TITLE
Update changelog for 0.24.0 release

### PR DESCRIPTION
**Pull request by dsimansk**
## Description

Update changelog entries for the next release.

/cc @rhuss @maximilien @navidshaikh

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Comment by dsimansk** [comment]
/hold 
Adding hold to prevent conflict with and to accommodate https://github.com/knative/client/pull/1328 if it's merged.

**Review by rhuss — COMMENTED** [review]
thanks !

/lgtm
/approve

**Pull request merged**
