### PR TITLE
Rename go files under command group dir

### PR DESCRIPTION
**Pull request by zhanggbj**
- Files under service dir
- Files under revision dir
- Files under plugin dir

[issue 229](https://github.com/knative/client/issues/229)

### CODE REVIEW

**Comment by zhanggbj** [comment]
@rhuss Thanks for your info! I understand it and will take a look later after the release is done.

**Comment by zhanggbj** [comment]
Hi @rhuss @maximilien @evankanderson,

I saw kn have built releases, so I rebased with master and also update all dir. Please help review again, thanks!

**Comment by zhanggbj** [comment]
Hi @maximilien 
Just noticed 1 check failed, and two files have `low Coverage`, does it mean we need to fill up test cases in this PR? Thanks!
```
Finding joining set of changed files from profile[count=13] & github
checking if this file is in github change list: pkg/kn/commands/plugin/handler.go	Yes!
checking if this file is in github change list: pkg/kn/commands/plugin/list.go	Yes!
checking if this file is in github change list: pkg/kn/commands/plugin/list_flags.go	Yes!
checking if this file is in github change list: pkg/kn/commands/plugin/verifier.go	Yes!
checking if this file is in github change list: pkg/kn/commands/revision/describe.go	Yes!
checking if this file is in github change list: pkg/kn/commands/revision/list.go	Yes!
checking if this file is in github change list: pkg/kn/commands/revision/list_flags.go	Yes!
checking if this file is in github change list: pkg/kn/commands/service/create.go	Yes!
checking if this file is in github change list: pkg/kn/commands/service/delete.go	Yes!	(Coverage low!)
checking if this file is in github change list: pkg/kn/commands/service/describe.go	Yes!
checking if this file is in github change list: pkg/kn/commands/service/list.go	Yes!
checking if this file is in github change list: pkg/kn/commands/service/list_flags.go	Yes!	(Coverage low!)
checking if this file is in github change list: pkg/kn/commands/service/update.go	Yes!
```

**Comment by zhanggbj** [comment]
HI Max @maximilien,

Just rebased but the test failed due to the `low code coverage`, does it mean we need to open another PR to fill up more test cases? Thanks!
```
checking if this file is in github change list: pkg/kn/commands/plugin/handler.go	Yes!
checking if this file is in github change list: pkg/kn/commands/plugin/list.go	Yes!
checking if this file is in github change list: pkg/kn/commands/plugin/list_flags.go	Yes!
checking if this file is in github change list: pkg/kn/commands/plugin/verifier.go	Yes!
checking if this file is in github change list: pkg/kn/commands/revision/describe.go	Yes!
checking if this file is in github change list: pkg/kn/commands/revision/list.go	Yes!
checking if this file is in github change list: pkg/kn/commands/revision/list_flags.go	Yes!
checking if this file is in github change list: pkg/kn/commands/route/describe.go	Yes!
checking if this file is in github change list: pkg/kn/commands/service/create.go	Yes!
checking if this file is in github change list: pkg/kn/commands/service/delete.go	Yes!	(Coverage low!)
checking if this file is in github change list: pkg/kn/commands/service/describe.go	Yes!
checking if this file is in github change list: pkg/kn/commands/service/list.go	Yes!
checking if this file is in github change list: pkg/kn/commands/service/list_flags.go	Yes!	(Coverage low!)
checking if this file is in github change list: pkg/kn/commands/service/update.go	Yes!
```

**Comment by navidshaikh** [comment]
@zhanggbj : I think that should be the way, just write another PR for missing unit tests in those files.

**Comment by zhanggbj** [comment]
**Note:** Please help review and merge https://github.com/knative/client/pull/399 firstly and then I'll rebase so we can pass the test here. Thanks!

**Comment by zhanggbj** [comment]
Hi @maximilien @navidshaikh 

It's ready for review, thx!

**Pull request merged**
