### PR TITLE
Connect using an OAuth2 JWT flow.

### PR DESCRIPTION
**Pull request by sixolet**
Allows you to connect using an oauth2 jwt flow if you have an appropriate json jwt key file.

An example of a "json jwt key file" is a Google Cloud Service account, so this fully solves #303 if you also have a kubeconfig about this minimal included:

```
apiVersion: v1
Kind: Config
clusters:
- cluster:
    server: https://us-central1-run.googleapis.com
  name: us-central1
users:
- name: u
contexts:
- context:
    user: u
    cluster: us-central1
    namespace: lol-its-my-project
  name: c
current-context: c
```

Invocation: 
```
kn service list  --jwt-key ~/my-key.json  --jwt-scope "https://www.googleapis.com/auth/cloud-platform"
```

The goal is to have this be an option for easily configuring kn from inside CI (and be easier than having to have a second oauth token printing command installed) if what you have is a jwt private key file.

### CODE REVIEW

**Comment by sixolet** [comment]
(experimental so far; doesn't have tests yet)

**Comment by rhuss** [comment]
Just to understand the scope of this PR:

* The functionality provided here could be equally achieved by preparing a proper kubeconfig file and using that with `--kubeconfig`. Is this correct ?
* Which other platforms (except of GCP) uses the same JWT based authentication ?

Without judging the usefulness of this PR, I see that it adds three new global options for a very specific use case. My general attitude is that we keep options at the possible minimum to not overwhelm users and so I always looking for how to keep the UX surface small or even reduce it (see also the discussion around logging/verbose/debug).  Adding three global options for a valid, but small use-case doesn't feel right to me.

I understand that it's easier to provide options to `kn` but what's about of having another (non-kn) program which just does the same but writes out that kubeconfig file which then could be used by kn.  This could be written in a single go file, compiled on the fly and run before `kn` is called. Not much more work for a CI and would help to keep kn focussed.

**Comment by sixolet** [comment]
> The functionality provided here could be equally achieved by preparing a proper kubeconfig file and using that with --kubeconfig. Is this correct ?

Unfortunately, you can't get a kubeconfig that does this on its own, usefully. The closest you can get is one that shells out to another command to go do an oauth flow and print out an appropriate bearer token, which is the walkthrough I listed in #303 — but that requires you have other software installed and configured. Alternately you can provide the bearer token in the kubectl, but then it'll expire in an hour. This document explains it: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens

> Which other platforms (except of GCP) uses the same JWT based authentication ?

According to that article, "notably Azure Active Directory, Salesforce, and Google"

> I understand that it's easier to provide options to kn but what's about of having another (non-kn) program which just does the same but writes out that kubeconfig file which then could be used by kn. This could be written in a single go file, compiled on the fly and run before kn is called. Not much more work for a CI and would help to keep kn focussed.

This might be workable, but I want to figure out something where a CI flow makes sense using a standard kn deployer image, even against providers that use jwt auth.  Maybe the answer is a previous step in CI needs to write the kubeconfig for them?

**Comment by sixolet** [comment]
... putting on hold for discussion

**Comment by rhuss** [comment]
@sixolet I wonder how we should proceed with this PR ? 

It would need some major refactoring because of the change in global config handling.
Do you want to continue to work on this PR or should be closed and the feature revisited at a later point in time ?

**Comment by rhuss** [comment]
@sixolet this PR is now nearly 1 year old. How should we progress ? I suggest we close it for now and then reopen it later ?

If you don't mind and you don't have any objections until next Tuesday, I would close the PR (but feel free to reopen it any time).

**Comment by rhuss** [comment]
closing it for now. feel free to rebase and reopen if the PR is still needed.

**Pull request closed without merging**
